[package]
name = "orwell_gtk"
version = "0.1.0"
authors = ["me@lucaszanella.com"]
edition = "2018"

[dependencies]
rand = "0.6.5"
gio = "^0"
gtk = { version = "^0", features=["v3_22"] }
gdk = "^0"
gl = "0.10"
epoxy = "0.0.4"
shared_library = "0.1.7"
libc = "0.2"